"""add current_building

Revision ID: 2f75e1a8e3a9
Revises: 36f97c444fe2
Create Date: 2026-02-05 09:35:59.050402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f75e1a8e3a9'
down_revision: Union[str, Sequence[str], None] = '36f97c444fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('current_building', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('experience_goals', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('proud_projects', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('other_interests', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'other_interests')
    op.drop_column('applications', 'proud_projects')
    op.drop_column('applications', 'experience_goals')
    op.drop_column('applications', 'current_building')
    # ### end Alembic commands ###
