"""Update review name

Revision ID: 36f97c444fe2
Revises:
Create Date: 2026-02-04 10:34:43.043440

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36f97c444fe2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_index(
        op.f('ix_achievements_sender_id'), 'achievements', ['sender_id'], unique=False
    )
    op.create_foreign_key(None, 'achievements', 'humans', ['sender_id'], ['id'])
    op.add_column('applications', sa.Column('sun_review', sa.String(), nullable=True))
    op.add_column(
        'applications', sa.Column('xiaoyu_review', sa.String(), nullable=True)
    )
    op.add_column('applications', sa.Column('frank_review', sa.String(), nullable=True))
    op.alter_column(
        'applications',
        'status',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        'applications',
        'discount_assigned',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_column('applications', 'timour_review')
    op.drop_column('applications', 'katherine_review')
    op.drop_column('applications', 'proud_projects')
    op.drop_column('applications', 'devon_review')
    op.drop_column('applications', 'experience_goals')
    op.drop_column('applications', 'Text')
    op.drop_column('applications', 'lina_review')
    op.drop_column('applications', 'current_building')
    op.drop_column('applications', 'janine_review')
    op.drop_column('applications', 'sophie_review')
    op.drop_column('applications', 'other_interests')
    op.drop_column('applications', 'tela_review')
    # Add FKs as NOT VALID (skip validating existing rows), then clean orphans and validate
    op.execute(
        'ALTER TABLE citizen_organizations '
        'ADD CONSTRAINT citizen_organizations_citizen_id_fkey '
        'FOREIGN KEY (citizen_id) REFERENCES humans(id) NOT VALID'
    )
    op.execute(
        'ALTER TABLE citizen_organizations '
        'ADD CONSTRAINT citizen_organizations_organization_id_fkey '
        'FOREIGN KEY (organization_id) REFERENCES organizations(id) NOT VALID'
    )
    op.execute(
        'DELETE FROM citizen_organizations '
        'WHERE citizen_id NOT IN (SELECT id FROM humans) '
        '   OR organization_id NOT IN (SELECT id FROM organizations)'
    )
    op.execute(
        'ALTER TABLE citizen_organizations VALIDATE CONSTRAINT citizen_organizations_citizen_id_fkey'
    )
    op.execute(
        'ALTER TABLE citizen_organizations VALIDATE CONSTRAINT citizen_organizations_organization_id_fkey'
    )
    op.add_column(
        'cluster_join_requests',
        sa.Column('target_citizen_id', sa.Integer(), nullable=False),
    )
    op.create_index(
        op.f('ix_cluster_join_requests_target_citizen_id'),
        'cluster_join_requests',
        ['target_citizen_id'],
        unique=False,
    )
    op.create_foreign_key(
        None, 'cluster_join_requests', 'humans', ['target_citizen_id'], ['id']
    )
    op.alter_column(
        'groups',
        'is_ambassador_group',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('false'),
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.alter_column(
        'popups', 'prefix', existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    op.create_unique_constraint(None, 'popups', ['prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'popups', type_='unique')
    op.alter_column(
        'popups', 'prefix', existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.alter_column(
        'groups',
        'is_ambassador_group',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text('false'),
    )
    op.drop_constraint(None, 'cluster_join_requests', type_='foreignkey')
    op.drop_index(
        op.f('ix_cluster_join_requests_target_citizen_id'),
        table_name='cluster_join_requests',
    )
    op.drop_column('cluster_join_requests', 'target_citizen_id')
    op.drop_constraint(
        'citizen_organizations_organization_id_fkey',
        'citizen_organizations',
        type_='foreignkey',
    )
    op.drop_constraint(
        'citizen_organizations_citizen_id_fkey',
        'citizen_organizations',
        type_='foreignkey',
    )
    op.add_column(
        'applications',
        sa.Column('tela_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('other_interests', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('sophie_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('janine_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('current_building', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('lina_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications', sa.Column('Text', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'applications',
        sa.Column('experience_goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('devon_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('proud_projects', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('katherine_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'applications',
        sa.Column('timour_review', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        'applications',
        'discount_assigned',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        'applications',
        'status',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column('applications', 'frank_review')
    op.drop_column('applications', 'xiaoyu_review')
    op.drop_column('applications', 'sun_review')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_index(op.f('ix_achievements_sender_id'), table_name='achievements')
    op.drop_column('achievements', 'sender_id')
    # ### end Alembic commands ###
